[sources.sql_database]
credentials = "mssql+pyodbc://@localhost/AdventureWorks2014?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes&trusted_connection=yes"

[destination.mssql.credentials]
database = "Lab5_BI"
password = ""
username = ""
host = "localhost"
port = 1433
driver = "ODBC Driver 18 for SQL Server"

[destination.mssql.credentials.query]
TrustServerCertificate = "yes"
Encrypt = "no"
Trusted_Connection = "yes"
LongAsMax = "yes"

[destination.duckdb.credentials]
database = "bi_lab5.duckdb"
